# -*- coding: utf-8 -*-
"""Deep Technical Blog on LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt6MofLrPYOzBOuuUXpDXMReYjhzg-XF
"""

# 🔥 Clean environment (fix all conflicts)
!pip uninstall -y numpy tensorflow jax jaxlib transformers langchain langchain-core langchain-community langchain-text-splitters langchain-openai

# ✅ Install compatible versions (NO CONFLICTS)
!pip install numpy==1.26.4
!pip install transformers==4.41.2
!pip install langchain==0.2.12
!pip install langchain-community==0.2.10
!pip install langchain-core==0.2.30
!pip install sentence-transformers==2.7.0

# Restart runtime after install
import os
os.kill(os.getpid(), 9)

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain.memory import ConversationBufferMemory

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

# ✅ Load model with better settings
pipe = pipeline(
    "text2text-generation",
    model="google/flan-t5-large",   # 🔥 upgrade model
    max_new_tokens=120,
    temperature=0.2,                # 🔥 reduce randomness
    do_sample=False                 # 🔥 deterministic output
)

llm = HuggingFacePipeline(pipeline=pipe)

# ✅ Strong prompt
prompt = "Explain LangChain clearly in 2-3 sentences for a beginner in AI."

response = llm.invoke(prompt)

print("🔹 LLM Output:")
print(response)

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

pipe = pipeline(
    "text2text-generation",
    model="google/flan-t5-large",
    max_new_tokens=120,
    do_sample=False
)

llm = HuggingFacePipeline(pipeline=pipe)

prompt = """
LangChain is a framework used for building applications with large language models.

.
"""

response = llm.invoke(prompt)

print("🔹 LLM Output:")
print(response)

from langchain.prompts import PromptTemplate

# ✅ Better grounded prompt
prompt = PromptTemplate.from_template("""
LangChain is a framework used for building applications with large language models.

Explain {topic} clearly in 2-3 sentences.
""")

# ✅ New syntax (NO deprecation)
chain = prompt | llm

# Run
output = chain.invoke({"topic": "LangChain"})

print("🔹 Chain Output:")
print(output)

from langchain.memory import ConversationBufferMemory
from langchain.prompts import PromptTemplate

memory = ConversationBufferMemory(return_messages=False)

prompt = PromptTemplate.from_template("""
You are a helpful AI tutor.

Conversation so far:
{history}

User: {input}
AI:
""")

chain = prompt | llm

print("\n🔹 Memory Output:")

# ---- TURN 1 ----
user_input = "Hello"
history = memory.load_memory_variables({})["history"]

response = chain.invoke({
    "history": history,
    "input": user_input
})

memory.save_context(
    {"input": user_input},
    {"output": response}
)

print(response)


# ---- TURN 2 ----
user_input = "What am I learning?"
history = memory.load_memory_variables({})["history"]

response = chain.invoke({
    "history": history,
    "input": user_input
})

memory.save_context(
    {"input": user_input},
    {"output": response}
)

print(response)

!pip install -U langchain transformers accelerate

!pip install -U langchain langchain-community transformers accelerate

from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline

from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline

# Create pipeline
pipe = pipeline(
    "text-generation",
    model="google/flan-t5-base",
    max_new_tokens=100
)

# Wrap in LangChain
llm = HuggingFacePipeline(pipeline=pipe)

# Test

!pip install -U langchain langchain-community langchain-core transformers accelerate

import re

# ---- SAFE CALCULATOR ----
def calculator(expr):
    try:
        return eval(expr)
    except:
        return None

# ---- FIXED EXTRACTION ----
def extract_expression(text):
    # extract everything after "What is"
    match = re.search(r'what is\s*(.*)', text.lower())

    if match:
        expr = match.group(1)

        # clean unwanted characters
        expr = re.sub(r'[^0-9\+\-\*/\(\)\.\s]', '', expr)

        return expr.strip()

    return None

# ---- DETECTOR ----
def is_math_expression(text):
    return "what is" in text.lower()

# ---- AGENT ----
def agent(query):
    print("User Query:", query)

    if is_math_expression(query):
        expr = extract_expression(query)

        print("🔧 Tool Used: Calculator")
        print("Expression:", expr)

        result = calculator(expr)

        return f"The result of {expr} is {result}."

    return "No computation required."

# ---- RUN ----
response = agent("What is (45 * 2) + 10?")
print("\n🔹 FINAL OUTPUT:\n")
print(response)